### ISSUE TITLE
求添加支持：http://www.pcbeta.com/portal.php?mod=rss

### ISSUE THREAD

**Issue by kkzzhizhou** [feedocean/rss2full#1]
返回结果：http://www.pcbeta.com/portal.php got mediatype is not supported(text/html)

**Comment by zhengchun** [comment]
`rss2full`没有识别出URL后面`?mod=rss`的参数问题。

**Comment by zhengchun** [comment]
https://github.com/feedocean/rss2full/releases/tag/v0.2.1
