### ISSUE TITLE
处理非标准xml订阅问题：https://laod.cn/feed/

### ISSUE THREAD

**Issue by kkzzhizhou** [feedocean/rss2full#2]
返回：XML syntax error on line 122: illegal character code U+0008

**Comment by zhengchun** [comment]
看了一下这个RSS源的输出，因为XML里的一条新闻标题包含了无效的unicode字符，没有`CDATA`声明转义，不属于BUG，属于RSS源问题，等这条新闻过不在RSS源出现就会正常。
