### ISSUE TITLE
Medium publication image

### ISSUE THREAD

**Issue by borFSU** [feedocean/rss2full#4]
For reference, the website I've used with rss2full: https://towardsdatascience.com/feed.

It's successful in obtaining the article text, but the images are blurry and unusable.  This is an issue with all the publications from Medium and affiliates.  Manually scraping the website, it looks like there are 3 <img> tags associated with each image rendered on the website.  I'm not much of a front end developer, so my knowledge as to why they set up their publications this way is beyond me.

I guess I was wondering if there was a way to tweak settings or introduce some logic to determine the desired img location.  There must be some initially baked in to grab only one of the image tags (maybe just the first one).

**Comment by zhengchun** [comment]
Medium uses "lazy-load" tech for image loading. It means it uses Javascript to load whole image when the page are ready. This project is not support this feature.

**Comment by borFSU** [comment]
Thanks for the clarification.
